# Generated by Django 3.1.7 on 2021-03-13 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210313_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.customer')),
                ('orderCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.orders')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
