# Generated by Django 3.1.7 on 2021-03-13 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='products',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
